% Group Project Specification
% 300958 Social Web Analytics
% Due Date: Friday of Week 13

# Aim

The Group Project provides us with a chance to analyse the Social Web
using knowledge obtained from this unit with assistance from a
computer based statistical package. For this project, we will focus on
identifying a chosen companies Twitter image.

# Method

To complete this project:

1. Read through this specification.

2. Form a group and register your group in the vUWS 300958 Project
   section.

3. Choose a company that is active on Twitter, check that it not
   already on the list of [company
   names](http://staff.scm.uws.edu.au/~lapark/300958/project/company_name2016.txt)
   and send Laurence an email with subject "[300958 Project Company]
   Group: x; Company: y", where x is your group number and y is your
   wanted wanted company Twitter handle.  (e.g. if group 12 were
   choosing Telstra, the email subject would be "[300958 Project
   Company] Group: 12; Company: Telstra"). If your project name is
   approved by Laurence, it will appear on the list of [company
   names](http://staff.scm.uws.edu.au/~lapark/300958/project/company_name2016.txt)
   within the week.  Note that a given company cannot be allocated to
   more than one group.

4. Complete the data analysis required by the specification.

5. Write up your analysis using your favourite word
   processing/typesetting program, making sure that all of the working
   is shown and that is it presented well.

6. Include the student declaration text on the front page of your
   report. Please make sure that the names and student numbers of each
   group member are clearly displayed on the front page.

7. Submit the report as a PDF by the due date.


# Group Size and Organisation

Students in groups of size 4 are to work together to complete
this project.  One project report is to be submitted per group.

The group must be formed by signing-up to a group within the Project
section of 300958 in vUWS.  It is not compulsory for all students in a
group to be from the same lab class, but it is generally a good idea.

Groups must be formed by the end of week 9. Once the group is formed,
A 'manager' should be nominated from within the group to be
responsible for submitting the report.


# Due date and Submission

The project report is due in by 11:59 p.m. on the Friday of week 13.
The report must be submitted as a PDF file using the assignment
submission facilities in the Project section of 300958 in vUWS.  Only
one student from each group (the manager) needs to submit the
assignment.


# Report Format

Once the required analysis is performed by the group, the members of
the group are to write up the analysis as a report. Remember that the
assessor will only see the groups report and will be marking the
group's analysis based on your report. Therefore the report should
contain a clear and concise description of the procedures carried out,
the analysis of results and any conclusions reached from the analysis.

The required analysis in this specification covers the material
presented in lectures and labs.  Students should use the computer
software R to carry out the required analysis and then present the results
from the analysis in the report.


# Marks

This project is worth 30% of your final grade, and so the project will
be marked out of 30. The project consists of four investigations
and will be marked using the following criteria:

--------------------------------------------------------------------------
Marks  Criteria Satisfied
-----  -------------------------------------------------------------------
0-5    One of the project parts have been completed correctly.

6-10   Two of the project parts have been completed correctly.

11-15  Three of the project parts have been completed correctly.

16-20  All of the project parts have been completed correctly.

21-25  The required work has been completed correctly and the company questions have been answered based on the results.
--------------------------------------------------------------------------

There are also five marks allocated to presentation (based on the
report formatting, style, grammar and mathematical notation). If the
report looks like something that would be submitted to an employer,
then the full five marks will be awarded.

If a report is submitted late, the maximum mark it can achieve will be
reduced by 10% (3 marks) per day. E.g., if a report is submitted five
days late, it can receive at most 15 marks.


# Declaration

*The following declaration must be included in a clearly visible and
readable place on the first page of the report.*

* * * * * * *

By including this statement, we the authors of this work, verify that:

- We hold a copy of this assignment that we can produce if the
  original is lost or damaged.

- We hereby certify that no part of this assignment/product has been
  copied from any other student's work or from any other source except
  where due acknowledgement is made in the assignment.

- No part of this assignment/product has been written/produced for us
  by another person except where such collaboration has been
  authorised by the subject lecturer/tutor concerned.

- We are aware that this work may be reproduced and submitted to
  plagiarism detection software programs for the purpose of detecting
  possible plagiarism (**which may retain a copy on its database
  for future plagiarism checking**).

- We hereby certify that we have read and understand what the School
  of Computing and Mathematics defines as minor and substantial
  breaches of misconduct as outlined in the learning guide for this
  unit.

**Note: An examiner or lecturer/tutor has the right not to mark this
  project report if the above declaration has not been added to the
  cover of the report.**

* * * * * * *

# Project Description


A company is investigating its public image and has approached your
team to identify what the public associates with the company name.
The company wants the four pieces of analysis to be performed.

## Analysis of Twitter language

In this section, we want to examine the language used in tweets.

1. Download the random sample of tweets
   [randomSample2016.csv](http://staff.scm.uws.edu.au/~lapark/300958/project/randomSample2016.csv),
   and load using `randomSample = read.csv("randomSample2016.csv")`
2. Use the `tm` library to construct a document-term matrix of term frequencies.
3. Sum the columns to obtain a vector of term frequencies summed over all tweets.
4. Compute the proportion of each term in the random sample, from the vector of term frequencies.
5. List the top 10 words and their proportion.

What do these words tell us about the random sample?

## Analysis of the company image on Twitter

In this section we want to examine if the tweets about the company are
of random topics, or if they contain specific information.

1. Use the `searchTwitter` function from the `twitteR` library to
   search for 1000 tweets about the company.
2. Combine the company tweets with the random sample of tweets from
   part 1 and construct the document-term matrix of term frequencies over
   all tweets.
3. Sum the rows associated to the company tweets to obtain a vector of
   term frequencies over all company tweets, and do the same for the
   random tweets.
4. Combine the two vectors (of company tweets and random tweets) to
   create a $2\times M$ table (where $M$ is the number of terms, and
   also the length of the vectors), then perform a $\chi^2$ test for
   independence on this table.

What do the results of the test tell us about the company tweets and
random sample of tweets?

## Connection between public and company.

In this section, we want to determine what the public and company are
tweeting about, when tweeting about the company.

1. Use the function `userTimeline` from the `twitteR` library to
   download the last 1000 tweets from the company.
2. Combine the tweets about the company from part 2 with the tweets
   from the company and cluster the tweets using an appropriate
   clustering method.
3. List the set of terms associated to each cluster.
4. Compute the proportion of company tweets in each cluster.

What do these results tell us about the tweet topics from the company
and public about the company?

## Company Image

By combining all of this information, what can we say about the
company's image on Twitter?  Also identify any problems with the
analytical process used in each part and how the results may have been
effected by these problem (do not include programming problems).

The company want the above four parts of analysis to be written up in
a professional report. Each part should have its own section of the
report and all questions should have thoughtful answers. Any code that
is used should be included and clearly explained (include comments in
the code).
