% Group Project Specification
% 300958 Social Web Analytics
% Due Date: Friday of Week 12

# Aim

The Group Project provides us with a chance to analyse the Social Web
using the knowledge obtained from this unit with assistance from a
computer based statistical package. For this project, we will focus on
[Twitter](http://www.twitter.com).

# Method

To complete this project:

1. Read through this specification

2. Form a group and register your group in the vUWS 300958 Project
   section.

3. Complete the data analysis required by the specification

4. Write up your analysis using your favourite word
   processing/typesetting program, making sure that all of the working
   is shown and that is it presented well.

5. Include the student declaration text on the front page of your
   report. Please make sure that the names and student numbers of each
   group member are clearly displayed on the front page.

6. Submit the report as a PDF by the due date.


# Group Size and Organisation

Students in groups of size 1, 2, or 3 are to work together to complete
this project.  One project report is to be submitted per group.

The group must be formed by signing-up to a group within the Project
section of 300958 in vUWS.  It is not compulsory for all students in a
group to be from the same lab class, but it is generally a good idea.

Groups must be formed by the end of week 9. Once the group is formed,
A `manager' should be nominated from within the group to be
responsible for submitting the report.


# Due date and Submission

The project report is due in by 11:59 p.m. on the Friday of week 12.
The report must be submitted as a PDF file using the assignment
submission facilities in the Project section of 300958 in vUWS.  Only
one student from each group (the manager) needs to submit the
assignment.


# Report Format

Once the required analysis is performed by the group, the members of
the group are to write up the analysis as a report. Remember that the
assessor will only see the groups report and will be marking the
group's analysis based on your report. Therefore the report should
contain a clear and concise description of the procedures carried out,
the analysis of results and any conclusions reached from the analysis.

The required analysis in this specification covers the material
presented in lectures and labs.  Students should use the computer
software R to carry out the required analysis and then present the results
from the analysis in the report.


# Marks

This project is worth 30% of your final grade, and so the project will
be marked out of 30.

When marking the reports, the assessors will adhere to the following
marking criteria:

---------------------------------------------------------------------
 Mark Criteria
----- ---------------------------------------------------------------
   NA Report Not Submitted. Equivalent to 0 when computing final mark.

    0 Report submitted, but incomprehensible.

  1-5 Report contains analysis, but not related to that requested by
      the specification.

 6-10 Report contains some of the analysis requested by the
      specification.

11-15 Report contains most of the analysis requested by the
      specification.

16-20 Report contains all of the analysis requested by the
      specification.

21-25 Report contains all of the analysis requested by the
      specification, with reasonable explanations of why the chosen
      analysis was performed.

26-30 Report contains all of the analysis requested by the
      specification, with reasonable explanations of why the chosen
      analysis was performed.  Further useful investigation was also
      performed that reduced any uncertainty in the previous analysis.
---------------------------------------------------------------------

A mark within the provided range is given based on the quality and
presentation of the information in the report.


If a report is submitted late, the maximum mark it can achieve will be
reduced by 10% (3 marks) per day. E.g., if a report is submitted five
days late, it can receive at most 15 marks.


# Declaration

*The following declaration must be included in a clearly visible and
readable place on the first page of the report.*

* * * * * * *

By including this statement, we the authors of this work, verify that:

- We hold a copy of this assignment that we can produce if the
  original is lost or damaged.

- We hereby certify that no part of this assignment/product has been
  copied from any other student's work or from any other source except
  where due acknowledgement is made in the assignment.

- No part of this assignment/product has been written/produced for us
  by another person except where such collaboration has been
  authorised by the subject lecturer/tutor concerned.

- We are aware that this work may be reproduced and submitted to
  plagiarism detection software programs for the purpose of detecting
  possible plagiarism (**which may retain a copy on its database
  for future plagiarism checking**).

- We hereby certify that we have read and understand what the School
  of Computing and Mathematics defines as minor and substantial
  breaches of misconduct as outlined in the learning guide for this
  unit.

**Note: An examiner or lecturer/tutor has the right not to mark this
  project report if the above declaration has not been added to the
  cover of the report.**

* * * * * * *

# Project Description

The company "Old School Business", also known as OSB wants to start
using social media to promote its business. They have approached your
team with a request to find what other businesses have done
successfully using social media.

OSB are particularly interested in using Twitter and so have asked
your group to perform the following analysis on Twitter.

To begin, find a company that has a Twitter handle with over 10,000
followers and 1000 tweets, then perform the following tasks using the
chosen Twitter handle.

## What to tweet

To be successful on Twitter, a company needs to provide useful
information to its followers. We will examine this information so that
we can suggest what OSB can tweet about.  We do not want to present
all tweets to OSB, so we must identify if there is a set of common
tweet themes. This process involves:

a. download the last 1000 tweets from the chosen Twitter handle,

b. visualise the 1000 tweets using multi-dimensional scaling, making
   sure an appropriate metric is used.

c. cluster the tweets from the set of tweets using an appropriate
   number of clusters,

d. examine a sample of the tweets in each cluster to determine the
   theme of each cluster.


## Who to follow

Following others in Twitter is the same as endorsing them. We want to
examine if there is any method in choosing who to follow. We believe
that it is best to follow others that tweet about topics we will tweet
about, but we are unsure if this is true. To examine this:

a. locate 10 friends of the chosen Twitter handle,

b. download the last 100 tweets of each friend, and for the chosen
   twitter handle.

c. construct a frequency table of words for each of the 11 twitter
   handles (one table per handle).

d. examine if there is a significant difference in the words used
   between the chosen Twitter handle and each of the ten friends.


## Following friends

We are unsure if friending your followers leads to an increase in
popularity. To examine this, we will:


a. obtain a sample of the 1.5 degree egocentric graph centred at the
   chosen Twitter handle.  The egocentric graph should contain a
   sample of ten of the chosen Twitter handle's most popular friends,
   and a sample of ten of the chosen Twitter handle's most popular
   followers.

b. compute the centrality score for Twitter handle in our graph.

c. identify which Twitter handles friend their followers.

d. examine if there is a correlation between a handle's centrality
   score and the number of followers it has friended.


OSB want the analysis performed by your group to be submitted to them
as a written report, where each part of the analysis is clearly
explained, so that the directors of the company can understand what
was done. OSB do not want pages of R code or R output in the report.

The report should be divided into sections and logically laid out, so
that the reader can quickly find wanted information.

Figures and tables should be used where needed.





