% Group Project Specification
% 300958 Social Web Analytics
% Due Date: Friday of Week 13

# Aim

The Group Project provides us with a chance to analyse the Social Web
using the knowledge obtained from this unit with assistance from a
computer based statistical package. For this project, we will focus on
[Twitter](http://www.twitter.com).

# Method

To complete this project:

1. Read through this specification

2. Form a group and register your group in the vUWS 300958 Project
   section.

3. Complete the data analysis required by the specification

4. Write up your analysis using your favourite word
   processing/typesetting program, making sure that all of the working
   is shown and that is it presented well.

5. Include the student declaration text on the front page of your
   report. Please make sure that the names and student numbers of each
   group member are clearly displayed on the front page.

6. Submit the report as a PDF by the due date.


# Group Size and Organisation

Students in groups of size 2, 3 or 4 are to work together to complete
this project.  One project report is to be submitted per group.

The group must be formed by signing-up to a group within the Project
section of 300958 in vUWS.  It is not compulsory for all students in a
group to be from the same lab class, but it is generally a good idea.

Groups must be formed by the end of week 9. Once the group is formed,
A `manager' should be nominated from within the group to be
responsible for submitting the report.


# Due date and Submission

The project report is due in by 11:59 p.m. on the Friday of week 12.
The report must be submitted as a PDF file using the assignment
submission facilities in the Project section of 300958 in vUWS.  Only
one student from each group (the manager) needs to submit the
assignment.


# Report Format

Once the required analysis is performed by the group, the members of
the group are to write up the analysis as a report. Remember that the
assessor will only see the groups report and will be marking the
group's analysis based on your report. Therefore the report should
contain a clear and concise description of the procedures carried out,
the analysis of results and any conclusions reached from the analysis.

The required analysis in this specification covers the material
presented in lectures and labs.  Students should use the computer
software R to carry out the required analysis and then present the results
from the analysis in the report.


# Marks

## Marks

This project is worth 30% of your final grade, and so the project will
be marked out of 30. The project consists of six investigations where
each investigation contributes equally to your final mark.

There are six parts to the project, each will be marked using the
following criteria:

--------------------------------------------------------------------------
Marks  Criteria Satisfied
-----  -------------------------------------------------------------------
0      The method does not lead to insightful analysis.

1      The method provides the reader with some understanding of the data.

2      The correct method leads to partially correct results and analysis.

3      The correct method leads to correct results and analysis.

4      The correct method leads to correct results and analysis, with an insightful aim and conclusion.
--------------------------------------------------------------------------

Also, the overall quality of the report will be marked using the
following criteria:

--------------------------------------------------------------------------
Marks  Criteria Satisfied
-----  -------------------------------------------------------------------
0      The report is poorly formatted and has little structure.

1      The report is structured to allow the reader to identify each problem.

2      The report is clearly structured and formatted.

3-4    The report is clearly structured and formatted, and correct grammar and
        mathematical notation is used.

5-6    The report has the look of a professional report (clearly structured
        and formatted, correct grammar and mathematical notation, and the report is
        written so that is flows from start to end, not as a series of four
        disjoint problems).
--------------------------------------------------------------------------

If a report is submitted late, the maximum mark it can achieve will be
reduced by 10% (3 marks) per day. E.g., if a report is submitted five
days late, it can receive at most 15 marks.


# Declaration

*The following declaration must be included in a clearly visible and
readable place on the first page of the report.*

* * * * * * *

By including this statement, we the authors of this work, verify that:

- We hold a copy of this assignment that we can produce if the
  original is lost or damaged.

- We hereby certify that no part of this assignment/product has been
  copied from any other student's work or from any other source except
  where due acknowledgement is made in the assignment.

- No part of this assignment/product has been written/produced for us
  by another person except where such collaboration has been
  authorised by the subject lecturer/tutor concerned.

- We are aware that this work may be reproduced and submitted to
  plagiarism detection software programs for the purpose of detecting
  possible plagiarism (**which may retain a copy on its database
  for future plagiarism checking**).

- We hereby certify that we have read and understand what the School
  of Computing and Mathematics defines as minor and substantial
  breaches of misconduct as outlined in the learning guide for this
  unit.

**Note: An examiner or lecturer/tutor has the right not to mark this
  project report if the above declaration has not been added to the
  cover of the report.**

* * * * * * *

# Project Description

Twitter is investigating a new method of presenting search results to
users.  A new method was proposed, but unfortunately, the employee who
proposed the method has left the company and refuses to release any
more information on the method. Your task is reverse engineer the
method by performing the steps for a chosen query and working out what
the ordering is giving. The new method for presenting search results,
along with questions from Twitter, are as follows:

1. Choose and submit a search phrase for approval. The search results
  must provide at least 100 tweets. How does Twitter order the search
  results (e.g. does the ordering depends on the query term
  appearances, the date of the tweet, ...?).

2. Using the Twitter API, create a weighted term index $W$ of the
  search result tweets and report the top 10 IDF weighted terms (not
  including the search terms). If there are any frequently occuring
  terms that are not words (e.g. parts of a URL), place them in the
  stop list and recompute the term weights. Are all of the top 10
  terms related?

3. Using the term index and an appropriate metric, compute a
  dissimilarity matrix $D$, containing the dissimilarity between all
  terms and use MDS to visualise the dissimilarity between terms. Do
  there appear to be clusters of terms?

4. Use the same metric as above to compute the number of clusters using
  the elbow method. Then perform the clustering and report the top 10
  terms of each cluster. Examine each of the top 10 words for each
  cluster and manually determine the theme/topic of each cluster of
  terms.

5. Create a term topic matrix $T$ and multiply it with $W$ to obtain
  the tweet topic matrix $Z$. Create the graph adjacency matrix $A =
  ZZ'$, where there is an edge between two tweets if they share a
  topic, and plot the graph of tweets. If the graph is not ergodic,
  then increase the number of terms in each topic to the top 20 words
  and recompute the graph. If only a few tweets are not connected,
  then these can be ignored.

6. Finally, compute the closeness centrality of each tweet in the graph
  and compare this ordering to the original tweet ordering (from the
  search results). Find a way to measure the difference between the
  two orderings and report the result. The set of tweets should have a
  difference ordering to the original search order. What are they now
  ordered by?

Twitter want the analysis of the new "search results ordering method"
to be written up in a professional report. Each part of the method
should have its own section of the report and all questions from
Twitter should have thoughtful answers. Any code that is used should
be included and clearly explained (include comments in the code).

