% Sentiment Analysis
% Laurence A. F. Park
% 20th of September 2013

```{r setup, include=FALSE}
opts_chunk$set(dev = 'pdf', fig.cap="")
```


# Sentiment

<http://en.wikipedia.org/wiki/Sentiment_analysis>


# Sentiment Analysis

Classifying the polarity of a piece of text (positive, neutral or
negative).

Advanced sentiment analysis examines the emotion behind the text
(e.g. excited, annoyed, surprised).


## Data Mining Methods

In this unit we have seen:

- Regression: predicting a real value $y$
- Clustering: gathering similar objects into groups

In this lecture we will introduce:

- Classification: predicting an ordinal value from a set.

We will focus on binary classification, meaning the set of ordinal
values is of size 2. These values are usually $\{True, False\}$,
$\{Yes, No\}$, or $\{0,1\}$.


## Classification

Classification is the task of assigning a class (category) to an
object based on its attributes (variables, features).

Classification is a similar task to regression, but regression
predicts a real value for each object.

Classification problems:

- Classify if this email is spam, given the words in the email.
- Classify if a patient has cancer, given the patients attributes.
- Classify if it will rain today, given the humidity of the past few days.
- Classify if there is a tank in this satellite image, given the pixel intensities and positions.
- Classify if a person is suitable for a job, given the contents of their Facebook page.


### Example

Classification:
$$
	[~0.3~1.2~-4.3~2~] \rightarrow \text{Spam}
$$
Regression:
$$
	[~0.3~1.2~-4.3~2~] \rightarrow 4.4
$$

## Binary Classification

Classification is to assign a class to an object. Binary
classification is assigning a class to an object where there are only
two classes to choose from. Binary classification is the most common
form of classification, since it is less complex than multi-class
classification, and it allows us to predict answers to Yes/No
(True/False) questions.

### Example

If we want to classify if an email is spam, we would construct a
classifier that takes attributes of an email as its parameters, and
returns True or False:
$$
	\text{is.spam}(\text{email}) \rightarrow \{True, False\}
$$

## Classifier Construction



## Training

## Testing

## Maximum Likelihood


# Classification of Sentiment


It is difficult to identify what part of text sets the sentiment.

Therefore to perform sentiment analysis, we will use a machine
learning to learn from a set of examples and automatically classify
new pieces of text.

Machine learning methods require a set of objects each with a set of
measured features and a class.  We want to examine the features and
make a prediction of the class.  To do this, we obtain many examples
of objects with their classes and learn the relationships between
them.


# Naive Bayes Classsifier
http://en.wikipedia.org/wiki/Naive_bayes






# Decision Tree

# Evaluation


False Positive Rate
False Negative Rate
True Positive Rate
True Negative Rate

