% Introduction to Social Networks
% Laurence A. F. Park and Glenn Stone
% March 22, 2005


# Algorithms in R

Installing packages requires the proxy to be setup:
http://support.rstudio.org/help/kb/faq/configuring-r-to-use-an-http-proxy
http://www.uws.edu.au/information_technology_services/its/servicedesk/proxy_settings

install.packages("twitteR")

If you can't get R to use the proxy, you can download the packages and install them locally

Get the package from here:
http://cran.r-project.org/web/packages/available_packages_by_name.html

Tell R where you saved it:
install.packages("/tmp/bigdata_0.1.tgz", repos=NULL)



# Accessing Information from the Social Web

## How can my program access the Web?

Web pages are designed for reading and easy navigation, and so it is
difficult for a program to extract information from them.

Most large sites have a database back end. Our programs would prefer
to talk to the database.

In this section, we will investigate how to automatically gather
information from Web sites.


## Scraping Web pages


If you can view information in a Web page, then you are able to write
a program to scrape the information into your database.

Scraping data requires knowledge of the HTML structure of the page.

\begin{block}{Example Web page scraping process}
\begin{enumerate}
\item Download the HTML from the desired URL
\item Parse the HTML into some data structure
\item Extract the portions at the desired positions (e.g. the first paragraph of the second div block).
\end{enumerate}
\end{block}

The Python library [BeautifulSoup](http://www.crummy.com/software/BeautifulSoup/) is an example of
software that assists in Web page scraping.


## Problems with Web page scraping

This Python program scrapes the date from the Bureau of Meteorology Web site:

```` {#scrape_temp .python .numberLines startFrom="100"}
import urllib2
from BeautifulSoup import BeautifulSoup
bom_url = "http://www.bom.gov.au/nsw/forecasts/sydney.shtml"

# download the HTML
html = urllib2.urlopen(bom_url).read()
# parse HTML
soup = BeautifulSoup(html)
# find the temperature in the HTML
max_temperature = soup.html.body.findAll('em',{"class" : "max"})[0].string
# print the result
print "The maximum temperature for today is " + max_temperature + " degrees."
`````````````````````````````````````````````````

The code is dependent on the formatting of the Web page and so will
break if the formatting changes.


## Parts of a URL


```
scheme://domain:port/path?query_string#fragment_id
```

- scheme: http, https, ftp, ftps, ssh, webdav, ...
- domain: either a domain name or IP address
- port: port number, defaults to 80 if not provided
- path: path to file on Web server
- query string: arguments for dynamic files
- fragment_id: tag identifying section of the file

### Example

Identify the parts of the URL:
```
http://www.google.com/search?client=safari&q=hello
```

## Accessing an API


An *Application Programming Interface* (API) provides us access to the
information in a structured format, allowing us to use the information
in other applications.

Web sites that provide an API, do so using a specific URL.

The SCEM seminar site has a two access points:

- The human readable form: [http://seminars.scem.uws.edu.au/detail.php?id=20](http://seminars.scem.uws.edu.au/detail.php?id=20)
- The computer readable form using the API: [http://seminars.scem.uws.edu.au/api.php?id=20](http://seminars.scem.uws.edu.au/api.php?id=20)

For an API to be effective, it must provide a consistent URL and data
format that allows backward compatibility.


## API data formats

An API should present data in a standard format to allow us to use
existing tools for parsing.

The main formats used are:

- XML
- YAML
- JSON

Each of these formats allow us to represent complex data structures.

## XML

The eXtensible Markup Language (XML) is a flexible language for representing information.
It allows us to store data in a human readable form making information more accessible.
Many organisations have adopted XML for use in their file formats (the
Microsoft format .docx is an XML file compressed using Zip).

## XML structure
 
### Tags

- Start tag: \<custard\>
- End tag: \</custard\>

### Elements

An XML element is any portion of the data encased in a start and end
tag: \<password\>This is my password\</password\>. Note that elements can
be nested to create a hierarchy of elements by placing elements within
the tags of another element.

### Attributes

XML attributes allow us to add information to a tag:
\<password computer="barney.scem.uws.edu.au"\>Password for barney\</password\>




## Example XML

~~~~ {#example_xml .xml .numberLines startFrom="100"}
<?xml version="1.0" encoding="ISO-8859-1"?>

<characters>
    <character id="Frodo">
        <name>Frodo Baggins</name>
        <race>Hobbit</race>
    </character>
    <character id="Aragorn">
        <name>Aragorn, son of Arathorn</name>
        <race>Human</race>
    </character>
</characters>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Problem

List all of the tags, elements and attributes of the above XML.


## YAML

YAML (YAML Ain't Markup Language) was designed as a data
representation language that can store data types from most high level
programming languages, and formatted so that it is easily read by
humans.

## YAML structure

### Tags

A YAML tag is a sequence of characters appearing before the associated
data. A tag and its associated data are separated by a colon ':'.

### Elements

A YAML element consists of a tag and associated data, all indented at
the same level, for example "password: this is my password".  Note
that elements can be nested to create a hierarchy of elements by
placing elements within the data portion of another element.

### Lists

A list of elements begin with a dash '-' and all elements are indented
at the same level.

## Example YAML

~~~~ {#example_yaml .yaml .numberLines startFrom="100"}
%YAML 1.1 # Characters from Middle Earth
---
characters:
    - character:
        id: Frodo
        name: Frodo Baggins
        race: Hobbit
    - character:
        id: Aragorn
        name: Aragorn, son of Arathorn
        race: Human
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### Problem

Identify all of the tags, elements and lists of the above YAML.


## JSON

JavaScript Object Notation (JSON) is the format in which data
structures are printed from javascript.  Since many Web applications
are written in javascript, JSON has become a standard for sharing
information between Web applications.

## JSON structure

### Tags

A JSON tag is similar to a YAML tag, but it is encased in double
quotes. E.g. "password".

### Elements

JSON elements, like YAML elements, consist of a tag and associated
data, but indentation is not needed.  Note that elements can be nested
to create a hierarchy of elements by placing elements within the data
portion of another element.

### Lists

A list of elements is encased in square brackets, e.g. ['apple', 'banana', 'carrot' ]



## Example JSON

~~~~ {#example_json .json .numberLines startFrom="100"}
{
    "characters":
    [
        {
            "id":"Frodo",
            "name":"Frodo Baggins",
            "race":"Hobbit"
        }, 
        {
            "id":"Aragorn",
            "name":"Aragorn, son of Arathorn",
            "race":"Human"
        }
    ]
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### Problem

Identify all of the tags, elements and lists of the above JSON.


## Authentication

Web sites offering an API usually require authentication to keep all
users accountable. Without authentication, a user could constantly
download information from a site, draining the sites resources and
limiting its bandwidth, without detection.

If all users are authenticated, then a site can limit the access time
or downloads, ensuring all users have a consistent quality of service.

Traditional authentication is to load the login page and provide your
username and password.

### Insecurity

APIs are for access by programs that perform a specific task
(e.g. list today's tweets). A program should not have full access to
your account.

## OAuth

OAuth is a standard for authorisation, that provides temporary
key for restricted access to a service.

To obtain the OAuth key, we must manually access the site and generate
a key with given access priviliages (read only, read and write, or
write only).  This key can then be provided to a program to
automatically access our account.

### ROAuth

We will be using the R library ROAuth to authenticate users through R.


## Facebook Graph API

Facebook offers an interface to test out queries before inserting them in a program:
[https://developers.facebook.com/tools/explorer](https://developers.facebook.com/tools/explorer)

To obtain an access token (for OAuth), you must login to a Facebook
account.

For more information on the Graph API:
[https://developers.facebook.com/docs/reference/api/](https://developers.facebook.com/docs/reference/api/)

### Example queries

``` {#facebook_api .sql}
https://graph.facebook.com/me?access_token=...
https://graph.facebook.com/me/friends?access_token=...
https://graph.facebook.com/me/mutualfriends/you?access_token=...
```
Note: "me" can be replaced with an ID, "you" must be replaced with an ID.

## Twitter API

Unfortunately, there is no Twitter explorer page. To get information
from Twitter, we must send a HTTP request containing our ID, the
access key and the query. The results are returned in JSON format.

There are many programming languages the provide access to the Twitter
API. We will use the R interface throughout this unit.

More information on the Twitter API is here:
[https://dev.twitter.com/docs/api/1.1](https://dev.twitter.com/docs/api/1.1)

### Accessing Information

Note that we have access to most of the information from Twitter, but
we usually only have access to our information and our friends
information from Facebook.

### TwitteR

We will be using the R library twitteR to access the Twitter API through R.

## Summary

- We can use R to write programs that interface with the Web.
- Data can be scraped from Web pages or accessed using their API.
- Web APIs provide data in either XML, YAML or JSON format.
- To ensure a specific quality of service, Web sites require
  authentication when using their API.
- Facebook and Twitter provide powerful APIs.

## Next Week

Simple Exposure Analysis
