% Assessing for Impact
% 300958 Social Web Analysis 
% Week 12 Lab Solutions

```{r setup, include=FALSE}
opts_chunk$set(fig.path='figure/week12-labsol-')
```

`r opts_chunk$set(prompt=TRUE, comment=NA, fig.cap="")`


# Difference in means


```{r echo=FALSE}
options(scipen=1, digits=2)
suppressWarnings(require(xtable, quietly=TRUE))
set.seed(56223)
sim.one = function(mb, ma, n) {
before = rpois(n, mb)
after = rpois(n, ma)
cat("before = ")
dput(before, control=NULL)
cat("after = ")
dput(after, control=NULL)
return(list(before = before, after = after))
}
```


Using the data:
```{r echo=FALSE}
x = sim.one(140,175,5)
before = x$before
after = x$after
```


```{r}
shuffleMean = function(before, after) {

  combined = c(before, after)
  chosen = sample(length(combined), size = length(before), replace = FALSE)
  shuffledBefore = combined[chosen]
  shuffledAfter = combined[-chosen]
  return(mean(shuffledAfter) - mean(shuffledBefore))
}

randDist = replicate(1000, shuffleMean(before, after))
hist(randDist)

# compute p value
meanDiff = mean(after) - mean(before)
print(meanDiff)
pVal = mean(abs(randDist) > abs(meanDiff))
print(pVal)
```


Using the $t$ test we obtain:
```{r}
t.test(before, after)
```




# BACI designs 

Using the data

```{r echo=FALSE}
set.seed(86755)
sim.two = function(BIm, AIm, BCm, ACm, n) {
BIx = rpois(n, 96)
AIx = rpois(n, 129)
BCx = rpois(n, 52)
ACx = rpois(n, 85)
cat("before.control = ")
dput(BCx, control=NULL)
cat("after.control = ")
dput(ACx, control=NULL)
cat("before.impact = ")
dput(BIx, control=NULL)
cat("after.impact = ")
dput(AIx, control=NULL)
return(list(BC = BCx, AC = ACx, BI = BIx, AI = AIx))
}
x = sim.two(96,129,52,85, 4)
before.control = x$BC
after.control = x$AC
before.impact = x$BI
after.impact = x$AI
```

## Shaping the data

```{r}
count = c(before.control, after.control, before.impact, after.impact)
n = 4
when = factor(c(rep("before", n), rep("after", n), rep("before", n),
       rep("after", n)), levels = c("before", "after"))
company = factor(c(rep("control", 2 * n), rep("impact", 2 * n)),
	levels = c("control","impact"))
d = data.frame(when = when, company = company, count = count)
print(d)
```

## Building the randomisation distribution


```{r}
suppressWarnings(library(dae, quietly = TRUE)) # for yates.effects()

m = aov(count ~ when + company, data = d) # fit the Null model (no gamma)
f = predict(m)   # computed expected values
r = residuals(m) # compute residuals

### permute residuals and replace
R = 1000
randDist = rep(0,R)
for (m in 1:R) {
    y = f + sample(r) # shuffle residuals and add to fitted
    # compute c and store in cSet
    randDist[m] = yates.effects(aov(y ~ when * company, data = d))[3]
}
hist(randDist)
```

## Computing the $p$ value

```{r}
# compute c from data
g = yates.effects(aov(count ~ when * company, data = d))[3]
print(g)
# compute p value
pVal = mean(abs(randDist) > abs(g))
print(pVal)
```

## Using AOV

```{r}
summary(aov(count ~ when*company, data = d))
```


